// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ContabilioDbContext))]
    [Migration("20260331170915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("backend.Models.FiscalAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserProfileCuit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileCuit");

                    b.ToTable("FiscalAlerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Pendiente: Carga de deducciones SIRADIG F.572 (Desde DB SQlite)",
                            Type = "critical",
                            UserCuit = "20-12345678-9"
                        },
                        new
                        {
                            Id = 2,
                            Message = "Próximo vencimiento Monotributo: 20 de de este mes.",
                            Type = "info",
                            UserCuit = "20-12345678-9"
                        });
                });

            modelBuilder.Entity("backend.Models.UserProfile", b =>
                {
                    b.Property<string>("Cuit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConyuge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cuit");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Cuit = "20-12345678-9",
                            AnnualRevenue = 48500000m,
                            ChildrenCount = 2,
                            Email = "juan.perez@example.com",
                            FullName = "PEREZ, JUAN BAUTISTA (DB)",
                            HasConyuge = true,
                            Province = "CABA",
                            Regime = "monotributo"
                        });
                });

            modelBuilder.Entity("backend.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserProfileCuit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileCuit");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 850000m,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Factura C",
                            UserCuit = "20-12345678-9"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1200000m,
                            Date = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Factura C",
                            UserCuit = "20-12345678-9"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 950000m,
                            Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Factura C",
                            UserCuit = "20-12345678-9"
                        });
                });

            modelBuilder.Entity("backend.Models.FiscalAlert", b =>
                {
                    b.HasOne("backend.Models.UserProfile", null)
                        .WithMany("Alerts")
                        .HasForeignKey("UserProfileCuit");
                });

            modelBuilder.Entity("backend.Models.Voucher", b =>
                {
                    b.HasOne("backend.Models.UserProfile", null)
                        .WithMany("Vouchers")
                        .HasForeignKey("UserProfileCuit");
                });

            modelBuilder.Entity("backend.Models.UserProfile", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
